---
description: Предупреждение компилятора (уровень 1) CS4014
title: Предупреждение компилятора (уровень 1) CS4014
ms.date: 08/18/2020
f1_keywords:
- CS4014
helpviewer_keywords:
- CS4014
ms.assetid: b9e7c029-eaa9-48d7-8b3c-9823772c9acb
ms.openlocfilehash: 6118ac43672dca053bee57fdf16ac68ad6d61aee
ms.sourcegitcommit: 05d0087dfca85aac9ca2960f86c5efd218bf833f
ms.translationtype: HT
ms.contentlocale: ru-RU
ms.lasthandoff: 03/27/2021
ms.locfileid: "105637550"
---
# <a name="compiler-warning-level-1-cs4014"></a><span data-ttu-id="26072-103">Предупреждение компилятора (уровень 1) CS4014</span><span class="sxs-lookup"><span data-stu-id="26072-103">Compiler Warning (level 1) CS4014</span></span>

<span data-ttu-id="26072-104">Так как этот вызов не ожидается, выполнение существующего метода продолжается до тех пор, пока вызов не будет завершен.</span><span class="sxs-lookup"><span data-stu-id="26072-104">Because this call is not awaited, execution of the current method continues before the call is completed.</span></span> <span data-ttu-id="26072-105">Рассмотрите возможность применения оператора `await` к результату вызова.</span><span class="sxs-lookup"><span data-stu-id="26072-105">Consider applying the `await` operator to the result of the call.</span></span>

<span data-ttu-id="26072-106">Текущий метод вызывает асинхронный метод, который возвращает класс <xref:System.Threading.Tasks.Task> или <xref:System.Threading.Tasks.Task%601> и не применяет оператор [await](../operators/await.md) к результату.</span><span class="sxs-lookup"><span data-stu-id="26072-106">The current method calls an async method that returns a <xref:System.Threading.Tasks.Task> or a <xref:System.Threading.Tasks.Task%601> and doesn't apply the [await](../operators/await.md) operator to the result.</span></span> <span data-ttu-id="26072-107">Вызов асинхронного метода запускает асинхронную задачу.</span><span class="sxs-lookup"><span data-stu-id="26072-107">The call to the async method starts an asynchronous task.</span></span> <span data-ttu-id="26072-108">Однако поскольку оператор `await` не применяется, программа продолжает выполнение, не ожидая завершения задачи.</span><span class="sxs-lookup"><span data-stu-id="26072-108">However, because no `await` operator is applied, the program continues without waiting for the task to complete.</span></span> <span data-ttu-id="26072-109">Обычно разработчику требуется другое поведение.</span><span class="sxs-lookup"><span data-stu-id="26072-109">In most cases, that behavior isn't what you expect.</span></span> <span data-ttu-id="26072-110">Обычно другие аспекты вызывающего метода зависят от результатов вызова или, как минимум, вызывающий метод должен завершиться до возврата из метода, который содержит вызов.</span><span class="sxs-lookup"><span data-stu-id="26072-110">Usually other aspects of the calling method depend on the results of the call or, minimally, the called method is expected to complete before you return from the method that contains the call.</span></span>

<span data-ttu-id="26072-111">Также важной проблемой является обработка исключений, возникающих в вызываемом асинхронном методе.</span><span class="sxs-lookup"><span data-stu-id="26072-111">An equally important issue is what happens to exceptions that are raised in the called async method.</span></span> <span data-ttu-id="26072-112">Исключение, возникающее в методе, который возвращает <xref:System.Threading.Tasks.Task> или <xref:System.Threading.Tasks.Task%601>, хранится в возвращенной задаче.</span><span class="sxs-lookup"><span data-stu-id="26072-112">An exception that's raised in a method that returns a <xref:System.Threading.Tasks.Task> or  <xref:System.Threading.Tasks.Task%601> is stored in the returned task.</span></span> <span data-ttu-id="26072-113">Если не ожидать задачу или явно не проверять исключения, исключение будет потеряно.</span><span class="sxs-lookup"><span data-stu-id="26072-113">If you don't await the task or explicitly check for exceptions, the exception is lost.</span></span> <span data-ttu-id="26072-114">Если ожидать задачу, ее исключение будет создано повторно.</span><span class="sxs-lookup"><span data-stu-id="26072-114">If you await the task, its exception is rethrown.</span></span>

<span data-ttu-id="26072-115">Рекомендуется всегда ожидать вызов.</span><span class="sxs-lookup"><span data-stu-id="26072-115">As a best practice, you should always await the call.</span></span>

<span data-ttu-id="26072-116">Рекомендуется отключать предупреждение, только если вы уверены, что не нужно ожидать завершения асинхронного вызова и что вызванный метод не создаст исключения.</span><span class="sxs-lookup"><span data-stu-id="26072-116">You should consider suppressing the warning only if you're sure that you don't want to wait for the asynchronous call to complete and that the called method won't raise any exceptions.</span></span> <span data-ttu-id="26072-117">В этом случае можно отключить предупреждение, присвоив переменной результат вызова задачи.</span><span class="sxs-lookup"><span data-stu-id="26072-117">In that case, you can suppress the warning by assigning the task result of the call to a variable.</span></span>

<span data-ttu-id="26072-118">В следующем примере показано, как вызвать предупреждение, как отключить его и как ожидать вызов.</span><span class="sxs-lookup"><span data-stu-id="26072-118">The following example shows how to cause the warning, how to suppress it, and how to await the call.</span></span>

```csharp
static async Task CallingMethodAsync(int millisecondsDelay)
{
    Console.WriteLine("  Entering calling method.");

    // Call #1.
    // Call an async method. Because you don't await it, its completion
    // isn't coordinated with the current method, CallingMethodAsync.
    // The following line causes warning CS4014.
    CalledMethodAsync(millisecondsDelay);

    // Call #2.
    // To suppress the warning without awaiting, you can assign the
    // returned task to a variable. The assignment doesn't change how
    // the program runs. However, recommended practice is always to
    // await a call to an async method.

    // Replace Call #1 with the following line.
    // Task delayTask = CalledMethodAsync(millisecondsDelay);

    // Call #3
    // To contrast with an awaited call, replace the unawaited call
    // (Call #1 or Call #2) with the following awaited call. Best
    // practice is to await the call.

    // await CalledMethodAsync(millisecondsDelay);

    Console.WriteLine("  Returning from calling method.");
}

static async Task CalledMethodAsync(int millisecondsDelay)
{
    Console.WriteLine("    Entering called method, starting and awaiting Task.Delay.");

    await Task.Delay(millisecondsDelay);

    Console.WriteLine("    Task.Delay is finished--returning from called method.");
}
```

<span data-ttu-id="26072-119">В этом примере при выборе Call #1 или Call #2, неожидаемый асинхронный метод `CalledMethodAsync` завершается после того, как завершатся вызвавший его метод `CallingMethodAsync` и метод, вызвавший этот метод.</span><span class="sxs-lookup"><span data-stu-id="26072-119">In the example, if you choose Call #1 or Call #2, the unawaited async method `CalledMethodAsync` finishes after both its caller `CallingMethodAsync` and the caller's caller is complete.</span></span> <span data-ttu-id="26072-120">Последняя строка в следующем выводе показывает, когда завершается вызванный метод.</span><span class="sxs-lookup"><span data-stu-id="26072-120">The last line in the following output shows you when the called method finishes.</span></span> <span data-ttu-id="26072-121">Вход и выход из обработчика событий, который вызывает `CallingMethodAsync` , в полном примере помечены в выводе.</span><span class="sxs-lookup"><span data-stu-id="26072-121">Entry to and exit from the event handler that calls `CallingMethodAsync` in the full example are marked in the output.</span></span>

```console
Entering the Click event handler.
  Entering calling method.
    Entering called method, starting and awaiting Task.Delay.
  Returning from calling method.
Exiting the Click event handler.
    Task.Delay is finished--returning from called method.
```

<span data-ttu-id="26072-122">Можно также отключить предупреждения компилятора с помощью директив [#pragma warning](../preprocessor-directives.md#pragma-warning).</span><span class="sxs-lookup"><span data-stu-id="26072-122">You can also suppress compiler warnings by using [#pragma warning](../preprocessor-directives.md#pragma-warning) directives.</span></span>

## <a name="example"></a><span data-ttu-id="26072-123">Пример</span><span class="sxs-lookup"><span data-stu-id="26072-123">Example</span></span>

<span data-ttu-id="26072-124">Следующее консольное приложение содержит методы из предыдущего примера.</span><span class="sxs-lookup"><span data-stu-id="26072-124">The following console application contains the methods from the previous example.</span></span> <span data-ttu-id="26072-125">Ниже описана настройка приложения.</span><span class="sxs-lookup"><span data-stu-id="26072-125">The following steps set up the application.</span></span>

1. <span data-ttu-id="26072-126">Создайте новое консольное приложение и присвойте ему имя `AsyncWarning`.</span><span class="sxs-lookup"><span data-stu-id="26072-126">Create a console application, and name it `AsyncWarning`.</span></span>
1. <span data-ttu-id="26072-127">В редакторе Visual Studio Code выберите файл *Program.cs*.</span><span class="sxs-lookup"><span data-stu-id="26072-127">In the Visual Studio Code Editor, choose the *Program.cs* file.</span></span>
1. <span data-ttu-id="26072-128">Замените код файла *Program.cs* на код, приведенный ниже.</span><span class="sxs-lookup"><span data-stu-id="26072-128">Replace the code in *Program.cs* with the following code.</span></span>

    ```csharp
    using System;
    using System.Threading.Tasks;

    namespace AsyncWarning
    {
        class Program
        {
            static async Task Main()
            {
                Console.WriteLine("Entering Main() application entry point.");

                int millisecondsDelay = 2000;
                await CallingMethodAsync(millisecondsDelay);

                Console.WriteLine("Exiting Main() application entry point.");

                await Task.Delay(millisecondsDelay + 500);
            }

            static async Task CallingMethodAsync(int millisecondsDelay)
            {
                Console.WriteLine("  Entering calling method.");

                // Call #1.
                // Call an async method. Because you don't await it, its completion
                // isn't coordinated with the current method, CallingMethodAsync.
                // The following line causes warning CS4014.
                // CalledMethodAsync(millisecondsDelay);

                // Call #2.
                // To suppress the warning without awaiting, you can assign the
                // returned task to a variable. The assignment doesn't change how
                // the program runs. However, recommended practice is always to
                // await a call to an async method.

                // Replace Call #1 with the following line.
                //Task delayTask = CalledMethodAsync(millisecondsDelay);

                // Call #3
                // To contrast with an awaited call, replace the unawaited call
                // (Call #1 or Call #2) with the following awaited call. Best
                // practice is to await the call.

                // await CalledMethodAsync(millisecondsDelay);

                Console.WriteLine("  Returning from calling method.");
            }

            static async Task CalledMethodAsync(int millisecondsDelay)
            {
                Console.WriteLine("    Entering called method, starting and awaiting Task.Delay.");

                await Task.Delay(millisecondsDelay);

                Console.WriteLine("    Task.Delay is finished--returning from called method.");
            }
        }

        // Output with Call #1 or Call #2. (Wait for the last line to appear.)

        // Entering Main() application entry point.
        //   Entering calling method.
        //     Entering called method, starting and awaiting Task.Delay.
        //   Returning from calling method.
        // Exiting Main() application entry point.
        //     Task.Delay is finished--returning from called method.

        // Output with Call #3, which awaits the call to CalledMethodAsync.

        // Entering Main() application entry point.
        //   Entering calling method.
        //     Entering called method, starting and awaiting Task.Delay.
        //     Task.Delay is finished--returning from called method.
        //   Returning from calling method.
        // Exiting Main() application entry point.
    }
    ```

1. <span data-ttu-id="26072-129">Нажмите клавишу <kbd>F5</kbd>, чтобы запустить программу.</span><span class="sxs-lookup"><span data-stu-id="26072-129">Select the <kbd>F5</kbd> key to run the program.</span></span>

<span data-ttu-id="26072-130">Ожидаемый результат отобразится в конце кода.</span><span class="sxs-lookup"><span data-stu-id="26072-130">The expected output appears at the end of the code.</span></span>

## <a name="see-also"></a><span data-ttu-id="26072-131">См. также</span><span class="sxs-lookup"><span data-stu-id="26072-131">See also</span></span>

- [<span data-ttu-id="26072-132">await</span><span class="sxs-lookup"><span data-stu-id="26072-132">await</span></span>](../operators/await.md)
- [<span data-ttu-id="26072-133">Асинхронное программирование с использованием ключевых слов async и await</span><span class="sxs-lookup"><span data-stu-id="26072-133">Asynchronous programming with async and await</span></span>](../../programming-guide/concepts/async/index.md)
